# Generated by Django 4.2.6 on 2023-10-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("uid", models.CharField(max_length=255)),
                ("avatar_url", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("encrypted_password", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.TextField(default="")),
                ("zip_code", models.CharField(default="", max_length=255)),
                ("state", models.CharField(default="", max_length=255)),
                ("country", models.CharField(default="", max_length=255)),
                ("description", models.TextField(default="")),
            ],
        ),
    ]
