# Generated by Django 4.2.6 on 2023-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0003_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
