# Generated by Django 4.2.6 on 2023-10-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0004_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
