# Generated by Django 4.2.6 on 2023-10-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0005_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
